# --- General configuration --- #

# --- MQTT configuration --- #
mqtt:
  uname: "sanda"
  passwd: "denmark"
  host: "147.228.124.230"
  port: 1883
  topic: "voicehome/#"

# --- Tornado webserver configuration --- #
tornado:
  port: 8881
  debug: True
  frontend_relative: "../frontend/"
  index_page: "index.html"

# --- Mongo database configuration --- #
mongo:
  host: "127.0.0.1"
  port: 27017

# --- Socket control interface configuration --- #
socket:
  host: "127.0.0.1"
  port: 7107
